### PR TITLE
 Enable Ctrl-h for Backspace Functionality

### LINKED ISSUE #252: Enable `Ctrl-h` for Backspace Functionality
Hi there, thank you for the great project. I like it in a snap!

I've noticed that, while executing `z`, `i`, `I`, `c`, and `/`, removing a character backward, the `Ctrl-H` does not work as expected while the backspace key does. I have a strong muscle memory for using `Ctrl-H` as a backspace alternative, this small discrepancy prevents me from using felix smoothly.

I think impact to existing users and complexity the changes will introduce should be minimal. I would be happy to contribute to this enhancement as the changes needed for this looks straightforward. If you agree with this suggestion, I can open a pull request. If not, please just close this issue. Your thoughts and comments would be appreciated. Thanks!

### PR DESCRIPTION
**Pull request by 0x6b**
This PR will allow users to use <kbd>Ctrl-h</kbd> as an alternative for the backspace key for the following commands:

- `z` (zoxide jump)
- `i`/`I` (insert mode)
- `c` (rename)
- `/` (search mode)

Closes #252

### CODE REVIEW

**Comment by kyoheiu** [comment]
Looks like this line disables the backspace key to work if Ctrl is not pressed in all cases:
```
KeyCode::Backspace | KeyCode::Char('h')
    if modifiers == KeyModifiers::CONTROL =>
```
To avoid this, we have to capture the modifiers like this:
```
                                        match (code, modifiers) {
                                            (KeyCode::Esc, KeyModifiers::NONE) => {
                                                go_to_info_line_and_reset();
                                                hide_cursor();
                                                state.move_cursor(state.layout.y);
                                                break 'zoxide;
                                            }
                                           ...
                                            (KeyCode::Backspace, KeyModifiers::NONE)
                                            | (KeyCode::Char('h'), KeyModifiers::CONTROL) => {

```
Could you fix this?

**Comment by 0x6b** [comment]
Ah thanks @kyoheiu for catching that! I'll revisit the PR with your suggestion. Please note that it'll be next month as I'm far away from my laptop recently.

**Comment by kyoheiu** [comment]
I see. Thank you for your time, I will be waiting:smile:

**Comment by 0x6b** [comment]
@kyoheiu I updated the branch with commits to address your comment. Can you please review the changes. Thanks!

**Comment by kyoheiu** [comment]
Thank you! There were some conflicts made by #255, so I resolved them and merge this PR.

**Comment by 0x6b** [comment]
Good catch @kyoheiu. Thanks for you help and release a new!

**Pull request merged**
