### PR TITLE
Adds ability to cd into last changed-to directory with ZZ

### PR DESCRIPTION
**Pull request by ElSamhaa**
- Adds a new keymap ZQ to exit fx without changing the directory
- Adds to README.md a tip to add the function to better integrate with unix shells

### CODE REVIEW

**Comment by kyoheiu** [comment]
Interesting. I gave this a try, and found the following:
- Even if `ZZ` does not work, it does not have to exit: The terminal screen should be cleaned up when exit.  It will go like this:
```
                                        KeyCode::Char('Z') => {
                                            //To communicate with the calling shell function for
                                            //subsequent use by cd
                                            if let Some(path) = state.lwd_file.to_owned() {
                                                std::fs::write(
                                                    path,
                                                    state.current_dir.to_str().unwrap(),
                                                )?;

                                                break 'main;
                                            } else {
                                                print_warning(
                                                    "env 'SHELL_PID' is not set.",
                                                    state.layout.y,
                                                );
                                            }
                                        }
```
(I can't push to your PR branch, so forgive me just pasting the code)

- As I set the bash function in `.bashrc`, I got this error message: `find: invalid argument `+1s' to `-mtime'`. (I COULD exit to the current directory though) How can we fix this? (And is this necessary?)

- Most important thing is, should we change `ZZ`'s role? As felix has used `ZZ` to exit to the same directory for a long time, users would be confused if `ZZ` does not work as they intend. Though I admit this is more `vim-like` way, I think it'd be better to keep `ZZ` as is, and use e.g. `:wq` (it must be a new key-mapping to not confuse) instead to realize this function: It must be a new key-mapping to not confuse.

**Comment by nate-sys** [comment]
what is the status of this? its a really neat feature

**Comment by ElSamhaa** [comment]
Sorry, this completely slipped my mind. I'll address @kyoheiu 's comments and push my changes.

**Comment by ElSamhaa** [comment]
@kyoheiu Updated the PR with changes in line with your comments.
I have added couple other enhancements:
- I've added a toggle to allow users to control whether or not to match the keybinding behavior of VIM. With that behavior switched off by default for backward-compatibility.
- I've optimized the shell integration shell script.

I've tested my changes under MacOS, Linux, Zsh and Bash.

**Comment by ElSamhaa** [comment]
@kyoheiu I have also added you the collaborators on my fork of `felix`. I'm not sure whether this helps with the fact that you can't edit the PR, but you can test and feedback me.

**Comment by nate-sys** [comment]
Tested on Void Linux - Bash. Works perfectly.

**Comment by kyoheiu** [comment]
Cool, it seems great! I'll test this PR in this weekend.

**Comment by kyoheiu** [comment]
I tried this PR on my Arch Linux and when exiting by `ZQ`, received error message, similar to before:

```
bash: bc: command not found
find: invalid argument `+' to `-mmin'
```
(though I succeeded to exit to the current dir)

I set `source <(command fx --init)` at the end of `.bashrc`. Could you tell me if something is wrong?

**Comment by ElSamhaa** [comment]
@kyoheiu Seems I was wrong in assuming that `bc` comes pre-installed _(Apparently it does not on Archlinux, while it does on the systems I'd tested on)_. I'll replace that arithmetic expression with its result which is static anyways `~ 0.02`. I only wrote it that way as a giveaway to my intent at the expense of the repeated cheap calculation.

The whole purpose of it is to remove any leftover LWD files everytime the `fx` function runs. I believe this might not be necessary as I can move that logic to run every time the `fx --init` is sourced instead; i.e every time an interactive shell is run.

**Comment by ElSamhaa** [comment]
@kyoheiu Updated the PR

**Comment by kyoheiu** [comment]
Works like a charm! Thank you. Looks good to me.

**Pull request merged**
