### PR TITLE
Safer terminal state management and better panic output

### LINKED ISSUE #118: panic when previewing symlink
The app panics when previewing a symlink.

**Version**: eeb98e31cd4489cf8683761ab23e0a22f9807e2a `felix v1.3.0: Up to date.` + chafa + zoxide

**Terminal**: iTerm2 + VSCode terminal (MacOS)

**Steps to reproduce**:
```
mkdir link-target
ln -s link-target link
ls -la link
# lrwxr-xr-x  1 user  staff  11 Oct 18 21:24 link -> link-target

fx
# presss 'v' to start preview
# navigate to `link`
```

**Details**:
In addition to the app panicking when previewing symlinks, the panic also borks the terminal session. Pressing Enter will not create new lines that start at the beginning, etc.

**rust_panic** output (produced via VSCode "Debug" main() session):
```
; id = {0x0000f445}, range = [0x00000001001e6520-0x00000001001e65b0), name="rust_panic"
; Source location: /rustc/e6a4afc3af2d2a53f91fc8a77bdfe94bea375b29/library/std/src/panicking.rs:743
1001E6520: FF 03 03 D1                sub    sp, sp, #0xc0
1001E6524: FD 7B 0B A9                stp    x29, x30, [sp, #0xb0]
1001E6528: FD C3 02 91                add    x29, sp, #0xb0
1001E652C: E0 87 00 A9                stp    x0, x1, [sp, #0x8]
1001E6530: E0 23 00 91                add    x0, sp, #0x8
1001E6534: C0 29 00 94                bl     0x1001f0c34  ; __rust_start_panic at lib.rs:107
1001E6538: E0 1F 00 B9                str    w0, [sp, #0x1c]
1001E653C: E8 73 00 91                add    x8, sp, #0x1c
1001E6540: 09 4B 10 10                adr    x9, #0x20960  ; core::fmt::num::imp::_$LT$impl$u20$core..fmt..Display$u20$for$u20$u32$GT$::fmt::hf8df51fe158b2d90 at num.rs:279
1001E6544: 1F 20 03 D5                nop    
1001E6548: 8A AC 39 10                adr    x10, #0x73590  ; log::LOG_LEVEL_NAMES::h4d63c3d47f15a313 + 9320
1001E654C: 1F 20 03 D5                nop    
1001E6550: A8 A7 3E A9                stp    x8, x9, [x29, #-0x18]
1001E6554: 28 00 80 52                mov    w8, #0x1
1001E6558: AA A3 3B A9                stp    x10, x8, [x29, #-0x48]
1001E655C: BF FF 3C A9                stp    xzr, xzr, [x29, #-0x38]
1001E6560: A9 63 00 D1                sub    x9, x29, #0x18
1001E6564: A9 A3 3D A9                stp    x9, x8, [x29, #-0x28]
1001E6568: A9 23 01 D1                sub    x9, x29, #0x48
1001E656C: 8A 70 0D 10                adr    x10, #0x1ae10  ; _$LT$core..fmt..Arguments$u20$as$u20$core..fmt..Display$GT$::fmt::h21a769ab7ab40008 at mod.rs:528
1001E6570: 1F 20 03 D5                nop    
1001E6574: E9 AB 05 A9                stp    x9, x10, [sp, #0x58]
1001E6578: 09 4C 39 10                adr    x9, #0x72980  ; log::LOG_LEVEL_NAMES::h4d63c3d47f15a313 + 6280
1001E657C: 1F 20 03 D5                nop    
1001E6580: 4A 00 80 52                mov    w10, #0x2
1001E6584: E9 AB 02 A9                stp    x9, x10, [sp, #0x28]
1001E6588: FF FF 03 A9                stp    xzr, xzr, [sp, #0x38]
1001E658C: E9 63 01 91                add    x9, sp, #0x58
1001E6590: E9 A3 04 A9                stp    x9, x8, [sp, #0x48]
1001E6594: A0 23 00 D1                sub    x0, x29, #0x8
1001E6598: E1 A3 00 91                add    x1, sp, #0x28
1001E659C: C0 E9 FF 97                bl     0x1001e0c9c  ; std::io::Write::write_fmt::hfbc9c4f0d9d445a6 at mod.rs:1633
1001E65A0: E0 13 00 F9                str    x0, [sp, #0x20]
1001E65A4: E0 83 00 91                add    x0, sp, #0x20
1001E65A8: B8 8A FF 97                bl     0x1001c9088  ; core::ptr::drop_in_place$LT$core..result..Result$LT$$LP$$RP$$C$std..io..error..Error$GT$$GT$::h825cba595bf1513d at mod.rs:486:1
1001E65AC: C7 12 00 94                bl     0x1001eb0c8  ; std::sys::unix::abort_internal::h4455c5e9af78a81a at mod.rs:258
```

### LINKED ISSUE #119: Terminal session not restored to original state
After closing `fx`, the terminal seems to be in a different state.

**Before**:
```
> someinput█  # <-- cursor character, e.g. '█', is visible
```

**After**:
```
> someinput   # <-- no cursor anymore
```

**Steps to reproduce**:
```
# observe original terminal state (e.g., cursor visible)

fx
# :q

# observe changed terminal state (e.g., cursor not visible anymore)
```

**Version**: eeb98e31cd4489cf8683761ab23e0a22f9807e2a `felix v1.3.0: Up to date.` + chafa + zoxide
Terminal state after exit changes in iTerm2 and in VSCode terminal (MacOS).
The effect is is even worse when the app panics. (https://github.com/kyoheiu/felix/issues/118)

**Solution Idea**:
1. Always save terminal state when starting an interactive terminal app that changes terminal state.
2. Always restore this state when exiting an interactive terminal app that changes terminal state.
3. Ensure restoration also works when your app panics to not leave users with a broken terminal.

### PR DESCRIPTION
**Pull request by ubunatic**
* manage panics in a safe `run` func
* rename unsafe `run` to `_run` func
* ensure terminal state is restored

Fixes #118   
Fixes #119

### CODE REVIEW

**Comment by kyoheiu** [comment]
I strongly agree that the application should not panic. But at the same time, I am not convinced that another crate, which looks very cool, is needed to handle the panic. Since this is a small program of about 4000 LOC, `scopeguard` seems a bit overkill.
Anyway, I'll consider your suggestion.

**Comment by ubunatic** [comment]
I removed scopeguard and added a manual restore after the unwind of the panic.

**Comment by kyoheiu** [comment]
Great! I learned a lot by this PR, thank you.
Added `clear_all()` and `move_to(1, 1)` (move cursor to top-left) to clear terminal state. How do you think?

**Comment by ubunatic** [comment]
> Great! I learned a lot by this PR, thank you. Added `clear_all()` and `move_to(1, 1)` (move cursor to top-left) to clear terminal state. How do you think?

Yes, why not. It makes a much cleaner output after the panic.

**Pull request merged**
