### PR TITLE
Add show/hide hidden files or dirs option

### PR DESCRIPTION
**Pull request by balroggg**
Closes https://github.com/kyoheiu/felix/issues/31

### CODE REVIEW

**Comment by kyoheiu** [comment]
I agree that it should be able to show/hide hidden items.
However, with this change, they will always be hidden at startup, right?
I think it would be better to allow the user to choose whether to hide it first, but I need a few days to decide if it is worth implementing the change in the config (since I want to keep felix simple).
Or maybe felix should store the setting in another file.

So, anyway, please wait a while.

**Comment by balroggg** [comment]
Yes, this pr hides hidden files/directories by default. Same behaviour like nautilus, ranger, vimfm.

**Comment by kyoheiu** [comment]
Merged. Thanks!
Better to keep the state of hide/show after exit, so I'll give it a try. In next release it'll come out.

**Comment by kyoheiu** [comment]
[Release v0.4.0 · kyoheiu/felix](https://github.com/kyoheiu/felix/releases/tag/v0.4.0)

**Comment by felixg3** [comment]
Is there a config setting? My installation of felix always reverts to showing hidden files.

**Comment by kyoheiu** [comment]
No, there is not a config for this. `backspace` key should toggle showing/hiding hidden items. (prefixed by `.`)

**Pull request merged**
